<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="35" failed="0" total="35" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="suite" duration-ms="29545" started-at="2021-12-11T18:21:25Z" finished-at="2021-12-11T18:21:55Z">
    <groups>
    </groups>
    <test name="Contact_US" duration-ms="38" started-at="2021-12-11T18:21:25Z" finished-at="2021-12-11T18:21:25Z">
      <class name="SanityTest.Contact_US">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:SanityTest.Contact_US@2c6a3f77]" name="beforeMethod" is-config="true" duration-ms="8" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Send_Message()[pri:0, instance:SanityTest.Contact_US@2c6a3f77]" name="Send_Message" duration-ms="10" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Configration.ConfigData.ClickOnBy_Xpath(ConfigData.java:113)
	at PageObjectModel.Contact_US_PO.ClickOnContactUS(Contact_US_PO.java:14)
	at SanityTest.Contact_US.Send_Message(Contact_US.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Send_Message -->
        <test-method status="FAIL" signature="afterMethod()[pri:0, instance:SanityTest.Contact_US@2c6a3f77]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Configration.ConfigData.teardown(ConfigData.java:72)
	at SanityTest.Contact_US.afterMethod(Contact_US.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:709)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="beforeMethod()[pri:0, instance:SanityTest.Contact_US@2c6a3f77]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Send_Message()[pri:0, instance:SanityTest.Contact_US@2c6a3f77]" name="Send_Message" duration-ms="0" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Send_Message -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:SanityTest.Contact_US@2c6a3f77]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- SanityTest.Contact_US -->
    </test> <!-- Contact_US -->
    <test name="Signin" duration-ms="4" started-at="2021-12-11T18:21:25Z" finished-at="2021-12-11T18:21:25Z">
      <class name="SanityTest.Signin">
        <test-method status="FAIL" signature="beforeMethod()[pri:0, instance:SanityTest.Signin@67b6d4ae]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()

	at SanityTest.Signin.beforeMethod(Signin.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="SignIn()[pri:0, instance:SanityTest.Signin@67b6d4ae]" name="SignIn" duration-ms="0" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignIn -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:SanityTest.Signin@67b6d4ae]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- SanityTest.Signin -->
    </test> <!-- Signin -->
    <test name="CheckSocialMediaLinks" duration-ms="29277" started-at="2021-12-11T18:21:25Z" finished-at="2021-12-11T18:21:54Z">
      <class name="SanityTest.CheckSocialMediaLinks">
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="beforeMethod" is-config="true" duration-ms="16519" started-at="2021-12-11T20:21:25Z" finished-at="2021-12-11T20:21:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="CheckFaceBookLink()[pri:1, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="CheckFaceBookLink" duration-ms="437" started-at="2021-12-11T20:21:42Z" finished-at="2021-12-11T20:21:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://web.facebook.com/groups/525066904174158/?_rdc=1&_rdr] but found [about:blank]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://web.facebook.com/groups/525066904174158/?_rdc=1&_rdr] but found [about:blank]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at PageObjectModel.CheckSocialMediaLinks_PO.IsFaceBookOpened(CheckSocialMediaLinks_PO.java:38)
	at SanityTest.CheckSocialMediaLinks.CheckFaceBookLink(CheckSocialMediaLinks.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckFaceBookLink -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="afterMethod" is-config="true" duration-ms="3605" started-at="2021-12-11T20:21:42Z" finished-at="2021-12-11T20:21:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="beforeMethod" is-config="true" duration-ms="8149" started-at="2021-12-11T20:21:46Z" finished-at="2021-12-11T20:21:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="CheckFaceBookLink()[pri:1, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="CheckFaceBookLink" duration-ms="82" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <exception class="org.openqa.selenium.NoSuchWindowException">
            <message>
              <![CDATA[Browsing context has been discarded
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'AHMADMALLOH', ip: '192.168.100.20', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [8d8182ee-a459-4e1f-afa9-78afda4e8520, findElement {using=id, value=social_block}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 95.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20211129150630, moz:debuggerAddress: localhost:56667, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 15372, moz:profile: C:\Users\User\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:56667/devtoo..., se:cdpVersion: 85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 8d8182ee-a459-4e1f-afa9-78afda4e8520]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchWindowException: Browsing context has been discarded
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'AHMADMALLOH', ip: '192.168.100.20', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [8d8182ee-a459-4e1f-afa9-78afda4e8520, findElement {using=id, value=social_block}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 95.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20211129150630, moz:debuggerAddress: localhost:56667, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 15372, moz:profile: C:\Users\User\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:56667/devtoo..., se:cdpVersion: 85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 8d8182ee-a459-4e1f-afa9-78afda4e8520
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:383)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:375)
	at PageObjectModel.CheckSocialMediaLinks_PO.ScrollInto_SocialMediaLinks(CheckSocialMediaLinks_PO.java:15)
	at SanityTest.CheckSocialMediaLinks.CheckFaceBookLink(CheckSocialMediaLinks.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:969)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1148)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchWindowException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckFaceBookLink -->
        <test-method status="FAIL" signature="afterMethod()[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[Failed to decode response from marionette
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'AHMADMALLOH', ip: '192.168.100.20', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [8d8182ee-a459-4e1f-afa9-78afda4e8520, quit {}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 95.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20211129150630, moz:debuggerAddress: localhost:56667, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 15372, moz:profile: C:\Users\User\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:56667/devtoo..., se:cdpVersion: 85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 8d8182ee-a459-4e1f-afa9-78afda4e8520]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: Failed to decode response from marionette
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'AHMADMALLOH', ip: '192.168.100.20', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [8d8182ee-a459-4e1f-afa9-78afda4e8520, quit {}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 95.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20211129150630, moz:debuggerAddress: localhost:56667, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 15372, moz:profile: C:\Users\User\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:56667/devtoo..., se:cdpVersion: 85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 8d8182ee-a459-4e1f-afa9-78afda4e8520
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.lambda$execute$1(DriverCommandExecutor.java:102)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="beforeMethod(java.lang.String)[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="CheckFaceBookLink()[pri:1, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="CheckFaceBookLink" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckFaceBookLink -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="beforeMethod(java.lang.String)[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="CheckYoutubeLink()[pri:3, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="CheckYoutubeLink" duration-ms="1" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckYoutubeLink -->
        <test-method status="SKIP" signature="CheckTwitterLink()[pri:2, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="CheckTwitterLink" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckTwitterLink -->
        <test-method status="SKIP" signature="beforeMethod(java.lang.String)[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="beforeMethod(java.lang.String)[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="CheckGoogleLink()[pri:4, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="CheckGoogleLink" duration-ms="1" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckGoogleLink -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:SanityTest.CheckSocialMediaLinks@3551a94]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- SanityTest.CheckSocialMediaLinks -->
    </test> <!-- CheckSocialMediaLinks -->
    <test name="AllActions_AtProduct" duration-ms="17" started-at="2021-12-11T18:21:54Z" finished-at="2021-12-11T18:21:54Z">
      <class name="SanityTest.AllActions_AtProduct">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="beforeTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()

	at SanityTest.AllActions_AtProduct.beforeTest(AllActions_AtProduct.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="beforeMethod()[pri:0, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Login()[pri:1, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="Login" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="SKIP" signature="SearchForProduct()[pri:2, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="SearchForProduct" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.AllActions_AtProduct.Login" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AllActions_AtProduct.SearchForProduct()[pri:2, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AllActions_AtProduct.SearchForProduct()[pri:2, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchForProduct -->
        <test-method status="SKIP" signature="SendProductToFriend()[pri:4, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="SendProductToFriend" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.AllActions_AtProduct.Login" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AllActions_AtProduct.SendProductToFriend()[pri:4, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AllActions_AtProduct.SendProductToFriend()[pri:4, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendProductToFriend -->
        <test-method status="SKIP" signature="WriteReviewOnProduct()[pri:3, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="WriteReviewOnProduct" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.AllActions_AtProduct.Login" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AllActions_AtProduct.WriteReviewOnProduct()[pri:3, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AllActions_AtProduct.WriteReviewOnProduct()[pri:3, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WriteReviewOnProduct -->
        <test-method status="SKIP" signature="AddProductToWishlist()[pri:5, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="AddProductToWishlist" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.AllActions_AtProduct.Login" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AllActions_AtProduct.AddProductToWishlist()[pri:5, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AllActions_AtProduct.AddProductToWishlist()[pri:5, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddProductToWishlist -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="SKIP" signature="AddProductToCart()[pri:6, instance:SanityTest.AllActions_AtProduct@2cb4c3ab]" name="AddProductToCart" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.AllActions_AtProduct.Login" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AllActions_AtProduct.AddProductToCart()[pri:6, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AllActions_AtProduct.AddProductToCart()[pri:6, instance:SanityTest.AllActions_AtProduct@2cb4c3ab] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddProductToCart -->
      </class> <!-- SanityTest.AllActions_AtProduct -->
    </test> <!-- AllActions_AtProduct -->
    <test name="Buy_Product" duration-ms="6" started-at="2021-12-11T18:21:54Z" finished-at="2021-12-11T18:21:54Z">
      <class name="SanityTest.Buy_Product">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:SanityTest.Buy_Product@13a57a3b]" name="beforeTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()

	at SanityTest.Buy_Product.beforeTest(Buy_Product.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="beforeMethod()[pri:0, instance:SanityTest.Buy_Product@13a57a3b]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Summary()[pri:2, instance:SanityTest.Buy_Product@13a57a3b]" name="Summary" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.Buy_Product.ChooseProduct" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Buy_Product.Summary()[pri:2, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Buy_Product.Summary()[pri:2, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Summary -->
        <test-method status="SKIP" signature="ChooseProduct()[pri:1, instance:SanityTest.Buy_Product@13a57a3b]" name="ChooseProduct" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ChooseProduct -->
        <test-method status="SKIP" signature="Signin()[pri:3, instance:SanityTest.Buy_Product@13a57a3b]" name="Signin" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.Buy_Product.Summary" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Buy_Product.Signin()[pri:3, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Buy_Product.Signin()[pri:3, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signin -->
        <test-method status="SKIP" signature="Address()[pri:4, instance:SanityTest.Buy_Product@13a57a3b]" name="Address" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.Buy_Product.Signin" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Buy_Product.Address()[pri:4, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Buy_Product.Address()[pri:4, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Address -->
        <test-method status="SKIP" signature="Payment()[pri:6, instance:SanityTest.Buy_Product@13a57a3b]" name="Payment" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.Buy_Product.Shipping" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Buy_Product.Payment()[pri:6, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Buy_Product.Payment()[pri:6, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Payment -->
        <test-method status="SKIP" signature="Shipping()[pri:5, instance:SanityTest.Buy_Product@13a57a3b]" name="Shipping" duration-ms="0" started-at="2021-12-11T20:21:54Z" depends-on-methods="SanityTest.Buy_Product.Address" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Buy_Product.Shipping()[pri:5, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Buy_Product.Shipping()[pri:5, instance:SanityTest.Buy_Product@13a57a3b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Shipping -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:SanityTest.Buy_Product@13a57a3b]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- SanityTest.Buy_Product -->
    </test> <!-- Buy_Product -->
    <test name="AddEmail_forNewsletter" duration-ms="6" started-at="2021-12-11T18:21:54Z" finished-at="2021-12-11T18:21:54Z">
      <class name="SanityTest.AddEmail_forNewsletter">
        <test-method status="FAIL" signature="beforeMethod()[pri:0, instance:SanityTest.AddEmail_forNewsletter@b97c004]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()

	at SanityTest.AddEmail_forNewsletter.beforeMethod(AddEmail_forNewsletter.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Add_EmailFor_News()[pri:1, instance:SanityTest.AddEmail_forNewsletter@b97c004]" name="Add_EmailFor_News" duration-ms="1" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Add_EmailFor_News -->
        <test-method status="SKIP" signature="beforeMethod()[pri:0, instance:SanityTest.AddEmail_forNewsletter@b97c004]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:SanityTest.AddEmail_forNewsletter@b97c004]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="Add_SameEmailFor_News()[pri:2, instance:SanityTest.AddEmail_forNewsletter@b97c004]" name="Add_SameEmailFor_News" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Add_SameEmailFor_News -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:SanityTest.AddEmail_forNewsletter@b97c004]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:54Z" finished-at="2021-12-11T20:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SanityTest.AddEmail_forNewsletter -->
    </test> <!-- AddEmail_forNewsletter -->
    <test name="Add_Update_DeleteAddress" duration-ms="6" started-at="2021-12-11T18:21:55Z" finished-at="2021-12-11T18:21:55Z">
      <class name="SanityTest.MyAccount.Add_Update_DeleteAddress">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c]" name="beforeTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()

	at SanityTest.MyAccount.Add_Update_DeleteAddress.beforeTest(Add_Update_DeleteAddress.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="beforeMethod()[pri:0, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Login()[pri:1, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c]" name="Login" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="SKIP" signature="AddNewAddress()[pri:2, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c]" name="AddNewAddress" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.Add_Update_DeleteAddress.Login" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Add_Update_DeleteAddress.AddNewAddress()[pri:2, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Add_Update_DeleteAddress.AddNewAddress()[pri:2, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddNewAddress -->
        <test-method status="SKIP" signature="UpdateAddress()[pri:3, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c]" name="UpdateAddress" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.Add_Update_DeleteAddress.AddNewAddress" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Add_Update_DeleteAddress.UpdateAddress()[pri:3, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Add_Update_DeleteAddress.UpdateAddress()[pri:3, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateAddress -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="SKIP" signature="DeleteAddress()[pri:4, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c]" name="DeleteAddress" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.Add_Update_DeleteAddress.UpdateAddress" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Add_Update_DeleteAddress.DeleteAddress()[pri:4, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Add_Update_DeleteAddress.DeleteAddress()[pri:4, instance:SanityTest.MyAccount.Add_Update_DeleteAddress@5afa04c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteAddress -->
      </class> <!-- SanityTest.MyAccount.Add_Update_DeleteAddress -->
    </test> <!-- Add_Update_DeleteAddress -->
    <test name="My_Wishlists" duration-ms="6" started-at="2021-12-11T18:21:55Z" finished-at="2021-12-11T18:21:55Z">
      <class name="SanityTest.MyAccount.My_Wishlists">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="beforeTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()

	at SanityTest.MyAccount.My_Wishlists.beforeTest(My_Wishlists.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="Login()[pri:1, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="Login" duration-ms="1" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="SKIP" signature="beforeMethod()[pri:0, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Create_Wishlist()[pri:2, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="Create_Wishlist" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.My_Wishlists.Login" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method My_Wishlists.Create_Wishlist()[pri:2, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method My_Wishlists.Create_Wishlist()[pri:2, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_Wishlist -->
        <test-method status="SKIP" signature="AddProduct_toWishlist()[pri:3, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="AddProduct_toWishlist" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.My_Wishlists.Create_Wishlist" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method My_Wishlists.AddProduct_toWishlist()[pri:3, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method My_Wishlists.AddProduct_toWishlist()[pri:3, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddProduct_toWishlist -->
        <test-method status="SKIP" signature="SendWithlist_toFriend()[pri:4, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="SendWithlist_toFriend" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.My_Wishlists.Create_Wishlist" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method My_Wishlists.SendWithlist_toFriend()[pri:4, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method My_Wishlists.SendWithlist_toFriend()[pri:4, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendWithlist_toFriend -->
        <test-method status="SKIP" signature="EditProduct_atWishlist()[pri:5, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="EditProduct_atWishlist" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.My_Wishlists.AddProduct_toWishlist" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method My_Wishlists.EditProduct_atWishlist()[pri:5, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method My_Wishlists.EditProduct_atWishlist()[pri:5, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EditProduct_atWishlist -->
        <test-method status="SKIP" signature="Delete_Wishlist()[pri:6, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="Delete_Wishlist" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.My_Wishlists.Create_Wishlist" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method My_Wishlists.Delete_Wishlist()[pri:6, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method My_Wishlists.Delete_Wishlist()[pri:6, instance:SanityTest.MyAccount.My_Wishlists@48eff760] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Delete_Wishlist -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:SanityTest.MyAccount.My_Wishlists@48eff760]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- SanityTest.MyAccount.My_Wishlists -->
    </test> <!-- My_Wishlists -->
    <test name="UpdatePersonal_Information" duration-ms="3" started-at="2021-12-11T18:21:55Z" finished-at="2021-12-11T18:21:55Z">
      <class name="SanityTest.MyAccount.UpdatePersonal_Information">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:SanityTest.MyAccount.UpdatePersonal_Information@1810399e]" name="beforeTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method getDriver(String) in the type ConfigData is not applicable for the arguments ()

	at SanityTest.MyAccount.UpdatePersonal_Information.beforeTest(UpdatePersonal_Information.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="beforeMethod()[pri:0, instance:SanityTest.MyAccount.UpdatePersonal_Information@1810399e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Login()[pri:1, instance:SanityTest.MyAccount.UpdatePersonal_Information@1810399e]" name="Login" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="SKIP" signature="UpdatePersonalnfo()[pri:2, instance:SanityTest.MyAccount.UpdatePersonal_Information@1810399e]" name="UpdatePersonalnfo" duration-ms="0" started-at="2021-12-11T20:21:55Z" depends-on-methods="SanityTest.MyAccount.UpdatePersonal_Information.Login" finished-at="2021-12-11T20:21:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method UpdatePersonal_Information.UpdatePersonalnfo()[pri:2, instance:SanityTest.MyAccount.UpdatePersonal_Information@1810399e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method UpdatePersonal_Information.UpdatePersonalnfo()[pri:2, instance:SanityTest.MyAccount.UpdatePersonal_Information@1810399e] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdatePersonalnfo -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:SanityTest.MyAccount.UpdatePersonal_Information@1810399e]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-12-11T20:21:55Z" finished-at="2021-12-11T20:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- SanityTest.MyAccount.UpdatePersonal_Information -->
    </test> <!-- UpdatePersonal_Information -->
  </suite> <!-- suite -->
</testng-results>
